### ISSUE TITLE
Optimising Scoring file

### ISSUE THREAD

**Issue by francicco** [EI-CoreBioinformatics/mikado#446]
Hi,

I'm at the final stage of annotating an ant genome with a very compact genome. I'm finding instances where `mikado pick` is not fully able to split annotations that span multiple genes.

Here an example:
<img width="616" alt="Screenshot 2023-09-22 at 10 26 42" src="https://github.com/EI-CoreBioinformatics/mikado/assets/9006870/663845ab-c764-4fe4-aabb-e67e4defae4e">

You can see how the black gene (g13343.t1) at the top, also very likely a BUSCO gene, is not transferred in the final annotation (blue transcripts at the bottom of the picture).

This is my scoring file:
```
requirements:
  expression: [((exon_num.multi and (cdna_length.multi or combined_cds_length.multi) and max_intron_length and min_intron_length and proportion_verified_introns_inlocus), or, (exon_num.mono and (combined_cds_length.mono or cdna_length.mono)))]
  parameters:
    cdna_length.mono: {operator: gt, value: 100}
    cdna_length.multi: {operator: ge, value: 100}
    combined_cds_length.mono: {operator: gt, value: 100}
    combined_cds_length.multi: {operator: gt, value: 100}
    exon_num.mono: {operator: eq, value: 1}
    exon_num.multi: {operator: gt, value: 1}
    max_intron_length: {operator: le, value: 150000}
    min_intron_length: {operator: ge, value: 20}
    proportion_verified_introns_inlocus: {operator: gt, value: 0}
not_fragmentary:
 expression: [((exon_num.multi and (cdna_length.multi or combined_cds_length.multi)), or, (exon_num.mono and combined_cds_length.mono))]
 parameters:
   exon_num.multi: {operator: gt, value: 1}
   cdna_length.multi: {operator: ge, value: 200}
   combined_cds_length.multi: {operator: gt, value: 100}
   exon_num.mono: {operator: eq, value: 1}
   combined_cds_length.mono: {operator: gt, value: 100}
scoring:
  blast_score: {rescaling: max}
  intron_fraction: {rescaling: max}
  exon_fraction: {rescaling: max}
  is_complete: {rescaling: target, value: true}
  selected_cds_locus_fraction: {rescaling: max}
  selected_cds_intron_fraction: {rescaling: max}
  selected_cds_length: {rescaling: max}
  selected_cds_fraction: {rescaling: target, value: 0.5}
  retained_fraction: {rescaling: min}
  proportion_verified_introns_inlocus: {rescaling: max}
  five_utr_length:
    filter: {operator: le, value: 1000}
    rescaling: target
    value: 100
  three_utr_length:
    filter: {operator: le, value: 1000}
    rescaling: target
    value: 200
  three_utr_num:
    filter: {operator: lt, value: 2}
    rescaling: target
    value: 1
  five_utr_num:
    filter: {operator: lt, value: 3}
    rescaling: target
    value: 2
  end_distance_from_junction:
    filter: {operator: lt, value: 55}
    rescaling: min
  verified_introns_num: {rescaling: max}
``` 

Is there anything you'd suggest to change and play with?
Thanks a lot
Francesco

**Comment by swarbred** [comment]
[reat_transcriptome_mikado_scoring_insect_noexpression_150723.yaml.zip](https://github.com/EI-CoreBioinformatics/mikado/files/12699972/reat_transcriptome_mikado_scoring_insect_noexpression_150723.yaml.zip)

Attached is the scoring config we use for insects within the reat transcriptome workflow (which uses mikado) https://reat.readthedocs.io/en/latest/index.html

The attached version is not using expression values (RPKM, FPKM) which we have as part of the pipeline.

This will penalise transcripts more with long muti exonic UTRs. Note the scoring is making use of portcullis junctions loaded in mikado serialise via the proportion_verified_introns_inlocus and proportion_verified_introns metrics so if you are not using this external data that would need to be adjusted.

I would expect Tr26683.1 and g13343.t1 to be selected from this region if the scoring is configured  as we do. Note you can run mikado pick just on this region with the -r option to check alternative scorings.

**Comment by francicco** [comment]
Hi @swarbred,

Thanks a lot for the tip, the new scoring file helped me a lot. But there's still something I don't understand.
I'm now restringing a bit my input annotation to Mikado to understand a bit better how it behave.

In this case for instance, the majority of the loci do not end in the final annotation.
<img width="1329" alt="Screenshot 2023-09-25 at 13 44 43" src="https://github.com/EI-CoreBioinformatics/mikado/assets/9006870/4444f77e-9f21-4425-9cd2-6aadd1766503">

`Scf0000001:8899678-8903160 - abstractlocus.py:1672 - WARNING - _check_requirements - LociProcesser-4 - Excluding from superlocus:Scf0000001+:8899678-8903160 because of failed requirements 1 transcripts out of 1: BUSCO_Tr267.1`

the splice sites are ok, I don't have clear why they are excluded.
Thanks a lot
F

**Comment by swarbred** [comment]
@francicco 

Check what you have in the requirements section of the scoring file, here BUSCO_Tr267.1 is not meeting those requirements and is therefore excluded upfront in pick

**Comment by francicco** [comment]
These are the requirements

```
requirements:
  expression: [((combined_cds_fraction.ncrna and exon_num.multi and canonical_intron_proportion) or (combined_cds_fraction.coding and is_complete)), and,
               ((exon_num.multi and only_non_canonical_splicing and (cdna_length.multi, or,  selected_cds_length.multi) and max_intron_length,
               and, min_intron_length and proportion_verified_introns_inlocus and (proportion_verified_introns or canonical_intron_proportion))
                      or (exon_num.mono and ((selected_cds_length.mono or cdna_length.mono) and selected_cds_fraction.mono))) ]
  parameters:
    combined_cds_fraction.ncrna: {operator: eq, value: 0}
    combined_cds_fraction.coding: {operator: gt, value: 0.20}
    selected_cds_fraction.mono: {operator: gt, value: 0.40}
    cdna_length.mono: {operator: gt, value: 100}
    cdna_length.multi: {operator: ge, value: 100}
    selected_cds_length.mono: {operator: gt, value: 100}
    selected_cds_length.multi: {operator: gt, value: 100}
    exon_num.mono: {operator: eq, value: 1}
    exon_num.multi: {operator: gt, value: 1}
    max_intron_length: {operator: le, value: 100000}
    min_intron_length: {operator: ge, value: 11}
    proportion_verified_introns_inlocus: {operator: gt, value: 0}
    proportion_verified_introns: {operator: gt, value: 0}
    is_complete: {operator: eq, value: true}
    canonical_intron_proportion: {operator: eq, value: 1}
    only_non_canonical_splicing: {operator: eq, value: false}
cds_requirements:
  expression: [combined_cds_length]
  parameters:
    combined_cds_length: {operator: ge, value: 0}
```

I don't see anything weird...
F

**Comment by francicco** [comment]
I think I got it... it was `is_complete: {operator: eq, value: true}`
F

**Comment by francicco** [comment]
Hi @swarbred,

another missed gene.
<img width="523" alt="Screenshot 2023-09-27 at 10 41 36" src="https://github.com/EI-CoreBioinformatics/mikado/assets/9006870/b09f6b01-6957-43e0-a56a-5da592a56eca">

It's a monoexotic transcript of 600nt and a CDS of 180nt, cds fraction of 0.30

I'm changing the score file but nothing. Isn't clear which requirements are not reached... maybe it should be listed in the log?
Thanks a lot
F

```
# Scoring file suitable for any species with intron sizes similar to mammals
requirements:
  expression: [((combined_cds_fraction.ncrna and exon_num.multi and canonical_intron_proportion) or (combined_cds_fraction.coding and is_complete)), and,
               ((exon_num.multi and only_non_canonical_splicing and (cdna_length.multi, or,  selected_cds_length.multi) and max_intron_length,
               and, min_intron_length and proportion_verified_introns_inlocus and (proportion_verified_introns or canonical_intron_proportion))
                      or (exon_num.mono and ((selected_cds_length.mono or cdna_length.mono) and selected_cds_fraction.mono))) ]
  parameters:
    combined_cds_fraction.ncrna: {operator: gt, value: 0}
    combined_cds_fraction.coding: {operator: gt, value: 0.40}
    selected_cds_fraction.mono: {operator: gt, value: 0.20}
    cdna_length.mono: {operator: gt, value: 100}
    cdna_length.multi: {operator: ge, value: 100}
    selected_cds_length.mono: {operator: gt, value: 100}
    selected_cds_length.multi: {operator: gt, value: 100}
    exon_num.mono: {operator: eq, value: 1}
    exon_num.multi: {operator: gt, value: 1}
    max_intron_length: {operator: le, value: 100000}
    min_intron_length: {operator: ge, value: 11}
    proportion_verified_introns_inlocus: {operator: gt, value: 0}
    proportion_verified_introns: {operator: gt, value: 0}
    is_complete: {operator: eq, value: false}
    canonical_intron_proportion: {operator: gt, value: 0}
    only_non_canonical_splicing: {operator: eq, value: false}
cds_requirements:
  expression: [combined_cds_length]
  parameters:
    combined_cds_length: {operator: ge, value: 0}
as_requirements:
  expression: [(combined_cds_fraction.ncrna and cdna_length and suspicious_splicing and max_intron_length) or (combined_cds_fraction.coding and cdna_length and three_utr_length and five_utr_length and utr_length and three_utr_num and five_utr_num and suspicious_splicing and max_intron_length and is_complete)]
  parameters:
    combined_cds_fraction.ncrna: {operator: eq, value: 0}
    combined_cds_fraction.coding: {operator: gt, value: 0.20}
    cdna_length: {operator: ge, value: 100}
    utr_length: {operator: le, value: 1000}
    five_utr_length: {operator: le, value: 500}
    three_utr_length: {operator: le, value: 500}
    suspicious_splicing: {operator: ne, value: true}
    max_intron_length: {operator: le, value: 50000}
    three_utr_num: {operator: lt, value: 2}
    five_utr_num: {operator: lt, value: 2}
    is_complete: {operator: eq, value: true}
not_fragmentary:
 expression: [((exon_num.multi and (cdna_length.multi or combined_cds_length.multi)), or, (exon_num.mono and combined_cds_length.mono))]
 parameters:
   is_complete: {operator: eq, value: false}
   exon_num.multi: {operator: gt, value: 1}
   cdna_length.multi: {operator: ge, value: 200}
   combined_cds_length.multi: {operator: gt, value: 100}
   exon_num.mono: {operator: eq, value: 1}
   combined_cds_length.mono: {operator: gt, value: 100}
scoring:
  blast_score: {rescaling: max, multiplier: 3}
  blast_target_coverage: {rescaling: max, multiplier: 3, use_raw: true}
  cdna_length: {rescaling: max}
  cds_not_maximal: {rescaling: min}
  cds_not_maximal_fraction: {rescaling: min}
  exon_num: {
    rescaling: max,
    filter: {
    operator: ge,
    value: 3}
  }
  five_utr_length:
    filter: {operator: le, value: 500}
    rescaling: target
    value: 400
  five_utr_num:
    filter: {operator: gt, value: 1}
    rescaling: max
    multiplier: -2
  end_distance_from_junction:
    filter: {operator: lt, value: 55}
    rescaling: min
  highest_cds_exon_number: {rescaling: max}
  intron_fraction: {rescaling: max}
  is_complete: {rescaling: target, value: true, multiplier: 2}
  number_internal_orfs: {rescaling: target, value: 1}
  non_verified_introns_num:
    rescaling: max
    multiplier: -3
    filter: {operator: gt, value: 1, metric: exon_num}
  proportion_verified_introns_inlocus:
    rescaling: min
    multiplier: -2
    filter: {operator: gt, value: 1, metric: exon_num}
  retained_fraction: {rescaling: min}
  retained_intron_num: {rescaling: min}
  selected_cds_fraction: {rescaling: target, value: 0.7}
  selected_cds_intron_fraction: {rescaling: max}
  selected_cds_length: {rescaling: max, multiplier: 3}
  selected_cds_num: {rescaling: max}
  num_introns_greater_than_max: {rescaling: max, multiplier: -3, filter: {operator: gt, value: 0}}
  three_utr_length:
    filter: {operator: le, value: 500}
    rescaling: target
    value: 800
  three_utr_num:
    filter: {operator: gt, value: 1}
    rescaling: max
    multiplier: -3
  end_distance_from_junction:
    filter: {operator: gt, value: 55}
    rescaling: max
    multiplier: -2
  combined_cds_locus_fraction: {rescaling: max}
  min_exon_length:
    filter: {operator: lt, value: 20}
    rescaling: min
    multiplier: -2
  utr_length:
    filter: {operator: gt, value: 500}
    rescaling: max
    multiplier: -3
```
